default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-json
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ['--django']

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [ "--rcfile=commit_pylintrc"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
